/*
 * File Purpose: Tournament template content definitions.
 * Key Mechanics: Provides event pools with fees, field sizes, rounds, and prize characteristics consumed each month.
 */

import type { TournamentTemplate } from '../models';

export const tournamentTemplates: TournamentTemplate[] = [
  {
    id: 'school_chess_festival',
    name: 'School Chess Festival',
    tier: 'Starter',
    format: 'swiss',
    fieldSize: 24,
    rounds: 5,
    avgOpponentRating: 780,
    ratingStdDev: 90,
    entryFee: 10,
    travelFatigue: 3,
    prizePool: 120,
    payoutScale: { first: 0.34, second: 0.24, third: 0.16, top8: 0.05 },
    minEloReq: 0,
    reputationReq: 0
  },
  {
    id: 'park_weekend_open',
    name: 'Park Weekend Open',
    tier: 'Starter',
    format: 'round_robin',
    fieldSize: 10,
    rounds: 6,
    avgOpponentRating: 860,
    ratingStdDev: 100,
    entryFee: 18,
    travelFatigue: 4,
    prizePool: 220,
    payoutScale: { first: 0.36, second: 0.24, third: 0.14, top8: 0.05 },
    minEloReq: 700,
    reputationReq: 0
  },
  {
    id: 'city_swiss_open',
    name: 'City Swiss Open',
    tier: 'Club',
    format: 'swiss',
    fieldSize: 32,
    rounds: 7,
    avgOpponentRating: 950,
    ratingStdDev: 120,
    entryFee: 30,
    travelFatigue: 6,
    prizePool: 400,
    payoutScale: { first: 0.4, second: 0.24, third: 0.13, top8: 0.045 },
    minEloReq: 850,
    reputationReq: 0
  },
  {
    id: 'district_youth_cup',
    name: 'District Youth Cup',
    tier: 'Club',
    format: 'swiss_top8_ko',
    fieldSize: 24,
    phase1Rounds: 5,
    rounds: 7,
    avgOpponentRating: 1120,
    ratingStdDev: 120,
    entryFee: 55,
    travelFatigue: 8,
    prizePool: 760,
    payoutScale: { first: 0.42, second: 0.24, third: 0.12, top8: 0.04 },
    minEloReq: 1000,
    reputationReq: 6
  },
  {
    id: 'regional_challenger',
    name: 'Regional Challenger',
    tier: 'Regional',
    format: 'swiss',
    fieldSize: 32,
    rounds: 7,
    avgOpponentRating: 1250,
    ratingStdDev: 140,
    entryFee: 80,
    travelFatigue: 9,
    prizePool: 1200,
    payoutScale: { first: 0.45, second: 0.25, third: 0.12, top8: 0.04 },
    minEloReq: 1150,
    reputationReq: 10
  },
  {
    id: 'state_junior_masters',
    name: 'State Junior Masters',
    tier: 'Regional',
    format: 'round_robin',
    fieldSize: 12,
    rounds: 8,
    avgOpponentRating: 1420,
    ratingStdDev: 150,
    entryFee: 110,
    travelFatigue: 10,
    prizePool: 1800,
    payoutScale: { first: 0.47, second: 0.24, third: 0.11, top8: 0.038 },
    minEloReq: 1325,
    reputationReq: 18
  },
  {
    id: 'masters_weekend',
    name: 'Masters Weekend Swiss',
    tier: 'National',
    format: 'swiss_top16_rr',
    fieldSize: 32,
    phase1Rounds: 5,
    rounds: 9,
    avgOpponentRating: 1550,
    ratingStdDev: 170,
    entryFee: 140,
    travelFatigue: 12,
    prizePool: 3200,
    payoutScale: { first: 0.5, second: 0.23, third: 0.1, top8: 0.035 },
    minEloReq: 1450,
    reputationReq: 25
  },
  {
    id: 'national_candidate_open',
    name: 'National Candidate Open',
    tier: 'National',
    format: 'swiss',
    fieldSize: 40,
    rounds: 9,
    avgOpponentRating: 1780,
    ratingStdDev: 180,
    entryFee: 220,
    travelFatigue: 14,
    prizePool: 5200,
    payoutScale: { first: 0.52, second: 0.22, third: 0.095, top8: 0.03 },
    minEloReq: 1650,
    reputationReq: 34
  },
  {
    id: 'continental_invitational',
    name: 'Continental Invitational',
    tier: 'Elite',
    format: 'round_robin',
    fieldSize: 14,
    rounds: 9,
    avgOpponentRating: 2050,
    ratingStdDev: 170,
    entryFee: 350,
    travelFatigue: 16,
    prizePool: 9000,
    payoutScale: { first: 0.55, second: 0.2, third: 0.09, top8: 0.028 },
    minEloReq: 1900,
    reputationReq: 50
  },
  {
    id: 'global_grand_prix',
    name: 'Global Grand Prix',
    tier: 'Elite',
    format: 'swiss_top4_ko',
    fieldSize: 32,
    phase1Rounds: 7,
    rounds: 10,
    avgOpponentRating: 2320,
    ratingStdDev: 140,
    entryFee: 600,
    travelFatigue: 20,
    prizePool: 18000,
    payoutScale: { first: 0.58, second: 0.19, third: 0.08, top8: 0.025 },
    minEloReq: 2200,
    reputationReq: 72
  },
  {
    id: 'scholars_cup_rapid',
    name: 'Scholars Cup Rapid',
    tier: 'Starter',
    format: 'round_robin',
    fieldSize: 8,
    rounds: 7,
    avgOpponentRating: 760,
    ratingStdDev: 80,
    entryFee: 8,
    travelFatigue: 3,
    prizePool: 80,
    payoutScale: { first: 0.36, second: 0.24, third: 0.16, top8: 0.05 },
    minEloReq: 0,
    reputationReq: 0
  },
  {
    id: 'metropolitan_open',
    name: 'Metropolitan Open',
    tier: 'Club',
    format: 'swiss_top2_ko',
    fieldSize: 28,
    phase1Rounds: 8,
    rounds: 9,
    avgOpponentRating: 1080,
    ratingStdDev: 130,
    entryFee: 46,
    travelFatigue: 7,
    prizePool: 620,
    payoutScale: { first: 0.4, second: 0.24, third: 0.13, top8: 0.042 },
    minEloReq: 980,
    reputationReq: 5
  },
  {
    id: 'international_junior_classic',
    name: 'International Junior Classic',
    tier: 'National',
    format: 'swiss_top8_ko',
    fieldSize: 36,
    phase1Rounds: 7,
    rounds: 10,
    avgOpponentRating: 1670,
    ratingStdDev: 175,
    entryFee: 210,
    travelFatigue: 14,
    prizePool: 4600,
    payoutScale: { first: 0.49, second: 0.22, third: 0.1, top8: 0.034 },
    minEloReq: 1550,
    reputationReq: 30
  },
  {
    id: 'elite_invitation_rr',
    name: 'Elite Invitational RR',
    tier: 'Elite',
    format: 'round_robin',
    fieldSize: 16,
    rounds: 11,
    avgOpponentRating: 2150,
    ratingStdDev: 120,
    entryFee: 420,
    travelFatigue: 17,
    prizePool: 11000,
    payoutScale: { first: 0.55, second: 0.2, third: 0.09, top8: 0.026 },
    minEloReq: 2000,
    reputationReq: 56
  }
];
